### ISSUE TITLE
The system cannot find the path specified. In windows 

### ISSUE THREAD

**Issue by chisunny** [r2-studio/robotmon-desktop#55]
I am getting the following error when starting the robotmon. Any idea what is the issue?

The system cannot find the path specified.
''' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:493:13)

**Comment by chisunny** [comment]
Fail when the code try to run the following command,

"nohup sh -c "LD_LIBRARY_PATH=/system/lib:/data/app/com.r2studio.robotmon-1/lib/arm:/data/app/com.r2studio.robotmon-2/lib/arm CLASSPATH=/data/app/com.r2studio.robotmon-1/base.apk:/data/app/com.r2studio.robotmon-2/base.apk app_process32 /system/bin com.r2studio.robotmon.Main $@" > /dev/null 2> /dev/null &';

**Comment by poi5305** [comment]
Which tool did you run?
start.exe, Service Manager (GUI) or command line

If command line, your first character is ", but should '
Full command:
adb shell 'nohup sh -c "LD_LIBRARY_PATH=/system/lib:/data/app/com.r2studio.robotmon-1/lib/arm:/data/app/com.r2studio.robotmon-2/lib/arm CLASSPATH=/data/app/com.r2studio.robotmon-1/base.apk:/data/app/com.r2studio.robotmon-2/base.apk app_process32 /system/bin com.r2studio.robotmon.Main $@" > /dev/null 2> /dev/null &'

You can quickly start "Robotmon Service" by using Service Manager tool
https://sites.google.com/view/robotmonen/document/quick-start
Step 4: Enable Robotmon service

**Comment by chisunny** [comment]
I am running the Robotmon Desktop. When I click start it gives that error. I am trying to use Robotmon Desktop to develop script.

Is there is way to use my own js script without using the Robotmon Desktop?

**Comment by poi5305** [comment]
Cloud you try Service Manager V1
https://github.com/r2-studio/robotmon-desktop/releases/download/v0.1/Robotmon-service-manager-v0.1.zip
Robotmon Desktop (current version, v1) is using old method to start the service.
