### ISSUE TITLE
Error trying to connect remote device in vscode extension

### ISSUE THREAD

**Issue by god-eater** [r2-studio/robotmon-desktop#90]
> [Error] Error getScreenSize 2, Response closed without headers, [object Object]
> [Error] Error listenLogs 2, Response closed without headers, [object Object]

Device: Nox ver. 6.3.0
OS: Windows 10, 
VS Code 1.38.1, ext ver. 0.0.4

**Comment by poi5305** [comment]
VSCode Extension currently only support Robotmon App Beta version. You cloud join the beta testing plan on Google Play.
